### ISSUE TITLE
how to work with the library?

### ISSUE THREAD

**Issue by posix-dev** [ibrabeicker/bezier#1]
Hello. 
You could help to figure out how your library is working?
If there are examples would be very happy to them.

**Comment by ibrabeicker** [comment]
Hello

You can use it by instantiating a BezierPath, parsing a [SVG bezier curve path](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#Bezier_Curves) with parsePathString and get any point in the curve by calling eval(float interp) where interp is between 0 and 1, 0 is at the start of the path, 1 is at the end. 

I initially used it for libGdx so the class Vector2 is from that framework, you can easily replace it by your own.

**Comment by posix-dev** [comment]
Many thanks.
